### ISSUE TITLE
Fail to Repeat Example 1

### ISSUE THREAD

**Issue by yxu148** [brian-team/brian2_paper_examples#1]
Hi,

I copied and pasted all codes from 
> example_1_pyloric_network.ipynb

and ran in Spyder with Python3.7.

I didn't run the plotting codes to test if the codes work. There is an error, and the error message says

> Cannot find Microsoft Visual Studio, You can try to set the path to vcvarsall.bat via the codegen.cpp.msvc_vars_location preference explicitly.

Should I use Visual Studio instead?

**Comment by mstimberg** [comment]
Hi @yxu148 . For efficiency reasons, the example switches on code generation for C++ with the line:
```
set_device('cpp_standalone', build_on_run=False)
```
For this to work, you need to have a working C++ compiler installed as explained here: https://brian2.readthedocs.io/en/stable/introduction/install.html#requirements-for-c-code-generation

Alternatively, you can remove the `set_device(...)` line – the simulation will run, but just not as fast.

**Comment by yxu148** [comment]
Hi Marcel,

Thanks for your reply. Problems solved!
